import type { Agent } from '@/types/agent'

export const mockAgents: Agent[] = [
  {
    id: '1',
    name: 'OutreachBot A1',
    department: 'SALES_DEPT',
    status: 'active',
    model: 'Llama 3.3',
    icon: { symbol: 'attach_money', bgColor: 'bg-blue-50', textColor: 'text-blue-600', borderColor: 'border-blue-100' },
    channels: [
      { icon: 'mail', title: 'Email' },
      { icon: 'work', title: 'LinkedIn' },
    ],
    lastActive: 'Just now',
    metricLabel: 'Tasks Queued',
    metricValue: '14',
    progressPercent: 75,
    progressColor: 'bg-accent-green',
  },
  {
    id: '2',
    name: 'HelpDesk 24/7',
    department: 'SUPPORT',
    status: 'active',
    model: 'Qwen 2.5',
    icon: { symbol: 'support_agent', bgColor: 'bg-purple-50', textColor: 'text-purple-600', borderColor: 'border-purple-100' },
    channels: [
      { icon: 'chat', title: 'Chat' },
    ],
    lastActive: '2m ago',
    metricLabel: 'Sentiment',
    metricValue: 'Positive',
    metricColor: 'text-accent-green',
    progressPercent: 45,
    progressColor: 'bg-purple-500',
  },
  {
    id: '3',
    name: 'BookingBot',
    department: 'OPS',
    status: 'paused',
    model: 'DeepSeek V3',
    icon: { symbol: 'calendar_month', bgColor: 'bg-amber-50', textColor: 'text-accent-gold', borderColor: 'border-amber-100' },
    channels: [
      { icon: 'event', title: 'Calendar' },
      { icon: 'mail', title: 'Email' },
    ],
    lastActive: '1h ago',
    metricLabel: 'Meetings Set',
    metricValue: '5',
    progressPercent: 20,
    progressColor: 'bg-accent-gold',
  },
  {
    id: '4',
    name: 'Analyst Pro',
    department: 'RESEARCH',
    status: 'active',
    model: 'Llama 3.3',
    icon: { symbol: 'travel_explore', bgColor: 'bg-pink-50', textColor: 'text-pink-500', borderColor: 'border-pink-100' },
    channels: [
      { icon: 'language', title: 'Web' },
    ],
    lastActive: '15s ago',
    metricLabel: 'Sources',
    metricValue: '142',
    progressPercent: 90,
    progressColor: 'bg-pink-500',
  },
  {
    id: '5',
    name: 'LedgerBot',
    department: 'FINANCE',
    status: 'error',
    model: 'Mistral Large',
    icon: { symbol: 'receipt_long', bgColor: 'bg-green-50', textColor: 'text-green-600', borderColor: 'border-green-100' },
    channels: [
      { icon: 'table_view', title: 'Spreadsheet' },
    ],
    lastActive: '2d ago',
    metricLabel: 'Status',
    metricValue: 'API Error',
    metricColor: 'text-red-500',
    progressPercent: 100,
    progressColor: 'bg-red-500',
  },
]
