-- Enable Row Level Security on all tables.
-- With zero permissive policies, PostgREST anon/authenticated roles
-- get zero rows and cannot write. The Express backend connects as
-- the database owner (bypasses RLS) and is unaffected.

ALTER TABLE IF EXISTS agents ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS messages ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS tasks ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS task_deps ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS chat_messages ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS chat_channels ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS approvals ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS sor_tables ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS sor_columns ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS sor_rows ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS sor_permissions ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS model_providers ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS agent_skills ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS teams ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS team_members ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS activity_log ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS notifications ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS notification_preferences ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS alert_preferences ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS goals ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS goal_tasks ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS team_subscriptions ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS team_credits ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS credit_transactions ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS model_credit_costs ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS skill_credit_costs ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS kpi_goals ENABLE ROW LEVEL SECURITY;
